import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://www.gstatic.com/firebasejs/4.1.3/firebase.js"></script>
        <script src="https://www.gstatic.com/firebasejs/4.1.3/firebase-auth.js"></script>
      </Head>
      <Sidebar></Sidebar>
    </div>
  )
}
